# Practice Notebook

### Setup

Import any packages you need in the following cell.

In [34]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Practice Exercises\n",
    "\n",
    "*Appying `numpy` to Conway's Game of Life.*\n",
    "\n",
    "We first introduced a model of the Game of Life as a way to introduce classes (objects). In this notebook we will instead use `numpy` to model the grid where our 'cells' live. Since it turns out that these cells do not require any more information that alive (1), or dead (0)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## *Task -- Setup*\n",
    "\n",
    "**Import `numpy` as `np`.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup imports.\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Questions\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "who_array = np.array([[[2,3,4,5], [1,2,3,4]], [[5,6,7,8], [1,2,3,4]]])\n",
    "\n",
    "print(who_array)\n",
    "\n",
    "you_array = np.append(who_array, [[[7], [8]], [[9], [1]]], axis=2)\n",
    "\n",
    "print(\"\\n\")\n",
    "\n",
    "print(you_array)\n",
    "\n",
    "me_array = np.append(you_array, [[[7], [4], [5], [4]]], axis=1)\n",
    "\n",
    "print(\"\\n\")\n",
    "\n",
    "print(me_array)\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5],\n",
       "        [1, 2, 3, 4]],\n",
       "\n",
       "       [[5, 6, 7, 8],\n",
       "        [1, 2, 3, 4]]])"
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array = np.array([[[2,3,4,5], [1,2,3,4]], [[5,6,7,8], [1,2,3,4]]])\n",
    "who_array"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2, 2, 4)"
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array.shape  # Dimsions 2, 0, 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5, 7],\n",
       "        [1, 2, 3, 4, 8]],\n",
       "\n",
       "       [[5, 6, 7, 8, 9],\n",
       "        [1, 2, 3, 4, 1]]])"
      ]
     },
     "execution_count": 83,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.append(who_array, [[[7], [8]], [[9], [1]]], axis=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 7, 8, 9, 1])"
      ]
     },
     "execution_count": 84,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.append(who_array, np.array([7, 8, 9, 1]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*Dimension Detail*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([7, 8, 9, 1])"
      ]
     },
     "execution_count": 85,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_array = np.array([7, 8, 9, 1])\n",
    "new_array"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(4,)"
      ]
     },
     "execution_count": 86,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_array.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We are trying to add to what dimension?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5],\n",
       "        [1, 2, 3, 4]],\n",
       "\n",
       "       [[5, 6, 7, 8],\n",
       "        [1, 2, 3, 4]]])"
      ]
     },
     "execution_count": 87,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[:, :, :]  # Get an entire copy, one slice per dimension."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5],\n",
       "        [1, 2, 3, 4]],\n",
       "\n",
       "       [[5, 6, 7, 8],\n",
       "        [1, 2, 3, 4]]])"
      ]
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[...]  # Another way."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[5, 4],\n",
       "       [8, 4]])"
      ]
     },
     "execution_count": 89,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[:, :, -1]  # Slice the last element from each dimension."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1, 2, 3, 4],\n",
       "       [1, 2, 3, 4]])"
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[:, -1, :]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[5, 6, 7, 8],\n",
       "       [1, 2, 3, 4]])"
      ]
     },
     "execution_count": 91,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[-1, :, :]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We want to add on to dimension `1`. What is the dimension of the slice we retrived?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2, 2)"
      ]
     },
     "execution_count": 92,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "who_array[:, :, -1].shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[7],\n",
       "        [8]],\n",
       "\n",
       "       [[9],\n",
       "        [1]]])"
      ]
     },
     "execution_count": 93,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_array.reshape(2, 2, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5, 7],\n",
       "        [1, 2, 3, 4, 8]],\n",
       "\n",
       "       [[5, 6, 7, 8, 9],\n",
       "        [1, 2, 3, 4, 1]]])"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.append(who_array, new_array.reshape(2, 2, 1), axis=2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Or, in the documentation, under **Array manipulation routines**:\n",
    "\n",
    ">...  \n",
    "`dstack(tup)` \tStack arrays in sequence depth wise (along third axis).  \n",
    "`hstack(tup)`\tStack arrays in sequence horizontally (column wise).  \n",
    "`vstack(tup)` \tStack arrays in sequence vertically (row wise).  \n",
    "..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[2, 3, 4, 5, 7],\n",
       "        [1, 2, 3, 4, 8]],\n",
       "\n",
       "       [[5, 6, 7, 8, 9],\n",
       "        [1, 2, 3, 4, 1]]])"
      ]
     },
     "execution_count": 95,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.dstack([who_array, new_array.reshape(2,2)])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Game of Life Overview\n",
    "\n",
    "\n",
    "The rules, as summarized by [Wolfram Alpha](http://mathworld.wolfram.com/GameofLife.html).\n",
    "\n",
    "> All eight of the cells surrounding the current one are checked to see if they are on or not. Any cells that are on are counted, and this count is then used to determine what will happen to the current cell.\n",
    "1. **Death**: if the count is less than 2 or greater than 3, the current cell is switched off.\n",
    "2. **Survival**: if (a) the count is exactly 2, or (b) the count is exactly 3 and the current cell is on, the current cell is left unchanged.\n",
    "3. **Birth**: if the current cell is off and the count is exactly 3, the current cell is switched on. \n",
    "\n",
    "It turns out that some people are *really* into this game. There are a large number of solutions available online, we will look at a few, and consider our own.\n",
    "\n",
    "\n",
    "#### Solutions Examined\n",
    "\n",
    "+ [Peter Norvig](https://nbviewer.jupyter.org/url/norvig.com/ipython/Life.ipynb) -- *Does not model a grid, instead keeps track of a set of cells (as coordinate tuples), then draws a grid. Entire thing runs in a jupyter notebook. Writes great (and fast) code, but has a tendancy to rename (alias) builtins.*\n",
    "+ [Holoviews Solution](http://holoviews.org/gallery/apps/bokeh/game_of_life.html#bokeh-gallery-game-of-life) -- *This implementation is exceptionally brief, as it is able to use some features from the `Holoviews` package, for drawing and 'ticking' the world.*\n",
    "\n",
    "\n",
    "*General Information:*  \n",
    "+ [See How seriously people are in to this.](http://www.conwaylife.com/)\n",
    "+ [Wikipidia Ariticle](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "![Breader pattern](https://upload.wikimedia.org/wikipedia/commons/e/e6/Conways_game_of_life_breeder_animation.gif)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Keep it Simple\n",
    "\n",
    "*Walk through of a simple solution.*\n",
    "\n",
    "Get it working first. Then try to make it better.\n",
    "\n",
    "### Building a Grid\n",
    "\n",
    "Recall that there are 'array constructor' functions in numpy that are nice for building up arrays."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n",
       "       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])"
      ]
     },
     "execution_count": 96,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# A 10 by 10 grid of dead cells.\n",
    "np.zeros((10, 10))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*Perhaps we want a randomly populated grid.*\n",
    "\n",
    "```python\n",
    "np.randint(low[, high, size, dtype])\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 1],\n",
       "       [0, 1, 1, 0, 1, 1, 0, 0, 1, 0],\n",
       "       [0, 0, 1, 0, 1, 1, 0, 0, 0, 1],\n",
       "       [1, 0, 0, 1, 0, 1, 0, 1, 1, 0],\n",
       "       [1, 1, 1, 0, 0, 0, 0, 0, 1, 1],\n",
       "       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0],\n",
       "       [0, 0, 1, 0, 1, 1, 1, 1, 1, 1],\n",
       "       [0, 1, 1, 1, 1, 1, 0, 0, 0, 0],\n",
       "       [0, 1, 1, 0, 0, 1, 1, 1, 1, 1],\n",
       "       [1, 0, 1, 0, 1, 1, 0, 0, 0, 1]])"
      ]
     },
     "execution_count": 97,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.random.randint(0, 2, (10, 10), np.int)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*These are all well and good, but if you want unique numbers to help wrap your head around indexing...*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],\n",
       "       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],\n",
       "       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],\n",
       "       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],\n",
       "       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],\n",
       "       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],\n",
       "       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],\n",
       "       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],\n",
       "       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],\n",
       "       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])"
      ]
     },
     "execution_count": 98,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_grid = np.arange(0, 100).reshape((10, 10))\n",
    "unique_grid"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Determining Fates\n",
    "\n",
    "*We will now impose time and our cruel will upon these innocent worlds.*\n",
    "\n",
    "How can we calculate if a cell should live or die?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Recall some indexing, start with getting just one cell.\n",
    "grid = np.random.randint(0, 2, (10, 10), np.int)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])"
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# These two calls are equivalent.\n",
    "assert all(unique_grid[0] == unique_grid[0, :])\n",
    "\n",
    "# Choose to be explicit when learning.\n",
    "unique_grid[0, :]  # A horizontal slize."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])"
      ]
     },
     "execution_count": 101,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_grid[:, 0]  # A vertical slice."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Slices can be passed too."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0,  1,  2],\n",
       "       [10, 11, 12],\n",
       "       [20, 21, 22]])"
      ]
     },
     "execution_count": 102,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_grid[0:3, 0:3]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[55, 56, 57],\n",
       "       [65, 66, 67],\n",
       "       [75, 76, 77]])"
      ]
     },
     "execution_count": 103,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_grid[5:8, 5:8]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Looping of the Array\n",
    "\n",
    "If you want to loop over something in Python, don't bother with indexes unless you have a specific order you need to go through. Simply call the object in a loop.\n",
    "\n",
    "*This usually access the __iter__() function of a given object.*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0 1 2 3 4 5 6 7 8 9]\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n"
     ]
    }
   ],
   "source": [
    "for row in unique_grid:\n",
    "    print(row)\n",
    "    for item in row:\n",
    "        print(item)\n",
    "    break  # Stop this loop."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**I want my loop and I want my numbers together or I am taking my ball and going home.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 0\n",
      "0 1\n",
      "0 2\n",
      "0 3\n",
      "0 4\n",
      "0 5\n",
      "0 6\n",
      "0 7\n",
      "0 8\n",
      "0 9\n"
     ]
    }
   ],
   "source": [
    "for row_index, row in enumerate(unique_grid):\n",
    "    for col_index, cell in enumerate(row):\n",
    "        print(row_index, col_index)\n",
    "    break"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Getting the Neighbors\n",
    "\n",
    "*And your little dog, too.*\n",
    "\n",
    "With the grid, indexing and looping in their first forms, we are ready to start composing functions. Let's write a function that loops over a given grid, and prints the coordinates of its 8 neighbors.\n",
    "\n",
    "*We can make an easy start by using some code from above:*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "metadata": {},
   "outputs": [],
   "source": [
    "def display_neighbor_coords(input_grid):\n",
    "    print(\"Showing current loop position...\")\n",
    "    for row_index, row in enumerate(input_grid):\n",
    "        for col_index, cell in enumerate(row):\n",
    "            print(row_index, col_index)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Test it with a smaller grid to avoid printing 100+ lines."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 1, 0],\n",
       "       [1, 1, 0],\n",
       "       [1, 1, 0]])"
      ]
     },
     "execution_count": 107,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_grid = np.random.randint(0, 2, (3, 3), np.int)\n",
    "test_grid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Showing current loop position...\n",
      "0 0\n",
      "0 1\n",
      "0 2\n",
      "1 0\n",
      "1 1\n",
      "1 2\n",
      "2 0\n",
      "2 1\n",
      "2 2\n"
     ]
    }
   ],
   "source": [
    "display_neighbor_coords(test_grid)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Actually getting the neighbors is separate from the loop. Come to think of it... If we want to know the coordinates of anyones neighbors, we need only know their coordinates."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_neighbor_indexes(x, y):\n",
    "    \"\"\"Return a set of indexes of the 8 neighbors to x, y.\"\"\"\n",
    "    return  [(x - 1, y + 1), (x, y + 1), (x + 1, y + 1),\n",
    "             (x - 1, y    ),             (x + 1, y    ),  # My actual 'center' (x, y) is in the hole here.\n",
    "             (x - 1, y - 1), (x, y - 1), (x + 1, y - 1)]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Why tuples?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(-1, 1), (0, 1), (1, 1), (-1, 0), (1, 0), (-1, -1), (0, -1), (1, -1)]"
      ]
     },
     "execution_count": 110,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_neighbor_indexes(0, 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 111,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(4, 6), (5, 6), (6, 6), (4, 5), (6, 5), (4, 4), (5, 4), (6, 4)]"
      ]
     },
     "execution_count": 111,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_neighbor_indexes(5, 5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Another approach would be to slice around the x, y location."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_neighbor_coors(grid, x, y):\n",
    "    return grid[x - 1 : x + 2, \n",
    "                y - 1 : y + 2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[11, 12, 13],\n",
       "       [21, 22, 23],\n",
       "       [31, 32, 33]])"
      ]
     },
     "execution_count": 113,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_neighbor_coors(unique_grid, 2, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[46, 47, 48],\n",
       "       [56, 57, 58],\n",
       "       [66, 67, 68]])"
      ]
     },
     "execution_count": 114,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_neighbor_coors(unique_grid, 5,7)  # Let's not concern ourselves with edge cases for now."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this case we could apply another 'mask' of booleans to remove thie center point."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 164,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ True,  True,  True],\n",
       "       [ True, False,  True],\n",
       "       [ True,  True,  True]])"
      ]
     },
     "execution_count": 164,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "bool_idx = np.array([[True, True, True], [True, False, True], [True, True, True]])\n",
    "bool_idx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 165,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([11, 12, 13, 21, 23, 31, 32, 33])"
      ]
     },
     "execution_count": 165,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_neighbor_coors(unique_grid, 2, 2)[bool_idx]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Consider the Life and Death Conditions\n",
    "\n",
    "First lets finalize an application of our neighbor fetching to a grid of 0 and 1."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 1, 0, 1, 1, 0, 1, 1, 0, 0],\n",
       "       [1, 1, 1, 0, 1, 1, 1, 0, 0, 0],\n",
       "       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0],\n",
       "       [0, 1, 1, 1, 1, 0, 0, 0, 1, 0],\n",
       "       [0, 0, 1, 1, 1, 0, 0, 0, 1, 0],\n",
       "       [1, 1, 0, 1, 0, 0, 1, 0, 0, 0],\n",
       "       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0],\n",
       "       [1, 1, 1, 1, 0, 1, 0, 1, 0, 0],\n",
       "       [1, 1, 0, 1, 0, 0, 1, 0, 1, 0],\n",
       "       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1]])"
      ]
     },
     "execution_count": 117,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "grid = np.random.randint(0, 2, (10, 10), np.int)\n",
    "grid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [],
   "source": [
    "def neighbors_1(grid, x, y):\n",
    "    return [grid[coords] for coords in get_neighbor_indexes(x, y)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[13, 23, 33, 12, 32, 11, 21, 31]"
      ]
     },
     "execution_count": 119,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "neighbors_1(unique_grid, 2, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[0, 1, 1, 1, 1, 1, 0, 1]"
      ]
     },
     "execution_count": 120,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "neighbors_1(grid, 2, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [],
   "source": [
    "def neighbors_2(grid, x, y):\n",
    "    bool_idx = np.array([[True, True, True], [True, False, True], [True, True, True]])\n",
    "    return get_neighbor_coors(grid, x, y)[bool_idx]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([11, 12, 13, 21, 23, 31, 32, 33])"
      ]
     },
     "execution_count": 122,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "neighbors_2(unique_grid, 2, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 1, 0, 0, 1, 1, 1, 1])"
      ]
     },
     "execution_count": 123,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "neighbors_2(grid, 2, 2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Calculating Life and Death\n",
    "\n",
    "> All eight of the cells surrounding the current one are checked to see if they are on or not. Any cells that are on are counted, and this count is then used to determine what will happen to the current cell.\n",
    "1. **Death**: if the count is less than 2 or greater than 3, the current cell is switched off.\n",
    "2. **Survival**: if (a) the count is exactly 2, or (b) the count is exactly 3 and the current cell is on, the current cell is left unchanged.\n",
    "3. **Birth**: if the current cell is off and the count is exactly 3, the current cell is switched on. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "metadata": {},
   "outputs": [],
   "source": [
    "def determine_fate(grid, x, y):\n",
    "    \n",
    "    neighbors = neighbors_2(grid, x, y)\n",
    "    \n",
    "    xy_state = grid[(x, y)]\n",
    "\n",
    "    print(f\"Center cell state: {xy_state}\")\n",
    "    \n",
    "    alive_neighbors = np.sum(neighbors)\n",
    "    print(f\"Alive neighbors: {alive_neighbors}\")\n",
    "    \n",
    "    if xy_state == 0 and alive_neighbors == 3:\n",
    "        print('Birth!')\n",
    "        return 1\n",
    "    \n",
    "    if xy_state == 1 and (alive_neighbors == 2 or alive_neighbors == 3):\n",
    "        print('Staying alive.')\n",
    "        return 1\n",
    "    \n",
    "    if xy_state == 1 and (alive_neighbors < 2 or alive_neighbors > 3):\n",
    "        print('Another one bites the dust.')\n",
    "        return 0\n",
    "\n",
    "    return None  # This is not needed, it is implicit."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Center cell state: 1\n",
      "Alive neighbors: 6\n",
      "Another one bites the dust.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 125,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "determine_fate(grid, 3, 3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "If only we could test it..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Nothing should happen here.\n",
    "test_1 = np.array([\n",
    "    [0, 0, 0],\n",
    "    [0, 0, 0],\n",
    "    [0, 0, 0]\n",
    "])\n",
    "\n",
    "# This cell should perish.\n",
    "test_2 = np.array([\n",
    "    [0, 0, 0],\n",
    "    [0, 1, 0],\n",
    "    [0, 0, 0]\n",
    "])\n",
    "\n",
    "# This cell should be born.\n",
    "test_3 = np.array([\n",
    "    [0, 1, 0],\n",
    "    [0, 0, 1],\n",
    "    [0, 1, 0]\n",
    "])\n",
    "\n",
    "\n",
    "# This cell should live.\n",
    "test_4 = np.array([\n",
    "    [0, 0, 0],\n",
    "    [0, 1, 0],\n",
    "    [0, 1, 1]\n",
    "])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`(1, 1)` should be the center, and the desired 'test cell'."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Center cell state: 0\n",
      "Alive neighbors: 0\n"
     ]
    }
   ],
   "source": [
    "determine_fate(test_1, 1, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Center cell state: 1\n",
      "Alive neighbors: 0\n",
      "Another one bites the dust.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 128,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "determine_fate(test_2, 1, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 129,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Center cell state: 0\n",
      "Alive neighbors: 3\n",
      "Birth!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 129,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "determine_fate(test_3, 1, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Center cell state: 1\n",
      "Alive neighbors: 2\n",
      "Staying alive.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 130,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "determine_fate(test_4, 1, 1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 131,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 143,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_world(grid, ticks=1000):\n",
    "    \n",
    "    for t in np.arange(ticks):\n",
    "        \n",
    "        # Calculate the fate of the cells.\n",
    "        \n",
    "        # Update (or replace) the grid.\n",
    "        \n",
    "        # Display the new grid.\n",
    "        \n",
    "        # Wait for the humans to grow complacent.\n",
    "        time.sleep(0.05)  # 1/20 seconds."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Plan your functions!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "# Holoviews Solution\n",
    "\n",
    "Examine what is happening here.\n",
    "\n",
    "```python\n",
    "def step(X):\n",
    "    nbrs_count = convolve2d(X, np.ones((3, 3)), mode='same', boundary='wrap') - X\n",
    "    return (nbrs_count == 3) | (X & (nbrs_count == 2))\n",
    "```\n",
    "\n",
    "The `convolve2d()` function is from the `scipy.signal` package. While we wont cover this function (or most of `scipy` in this class, a quick dive into another package can make a good lesson. See if you can figure out what the function above does with the help of the code below."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 134,
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy.signal import convolve2d"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "metadata": {},
   "outputs": [],
   "source": [
    "def test_convolve2d(in1, in2, mode='full', boundary='fill', fillvalue=0):\n",
    "    # The defualt arguments for the function are filled above.\n",
    "    print('Input array:')\n",
    "    print(in1)\n",
    "    out = convolve2d(in1, in2, mode, boundary, fillvalue)\n",
    "    print('Output:')\n",
    "    print(out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 136,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input array:\n",
      "[[0 0 0]\n",
      " [0 0 0]\n",
      " [0 0 0]]\n",
      "Output:\n",
      "[[0. 0. 0.]\n",
      " [0. 0. 0.]\n",
      " [0. 0. 0.]]\n"
     ]
    }
   ],
   "source": [
    "test_convolve2d(test_1, np.ones((3, 3)), mode='same')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 137,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input array:\n",
      "[[0 0 0]\n",
      " [0 1 0]\n",
      " [0 0 0]]\n",
      "Output:\n",
      "[[1. 1. 1.]\n",
      " [1. 1. 1.]\n",
      " [1. 1. 1.]]\n"
     ]
    }
   ],
   "source": [
    "test_convolve2d(test_2, np.ones((3, 3)), mode='same')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input array:\n",
      "[[0 1 0]\n",
      " [0 0 1]\n",
      " [0 1 0]]\n",
      "Output:\n",
      "[[1. 2. 2.]\n",
      " [2. 3. 3.]\n",
      " [1. 2. 2.]]\n"
     ]
    }
   ],
   "source": [
    "test_convolve2d(test_3, np.ones((3, 3)), mode='same')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input array:\n",
      "[[0 0 0]\n",
      " [0 1 0]\n",
      " [0 1 1]]\n",
      "Output:\n",
      "[[1. 1. 1.]\n",
      " [2. 3. 3.]\n",
      " [2. 3. 3.]]\n"
     ]
    }
   ],
   "source": [
    "test_convolve2d(test_4, np.ones((3, 3)), mode='same')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 140,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input array:\n",
      "[[0 1 0 1 1 0 1 1 0 0]\n",
      " [1 1 1 0 1 1 1 0 0 0]\n",
      " [1 0 0 1 0 0 0 0 1 0]\n",
      " [0 1 1 1 1 0 0 0 1 0]\n",
      " [0 0 1 1 1 0 0 0 1 0]\n",
      " [1 1 0 1 0 0 1 0 0 0]\n",
      " [0 1 0 0 1 0 0 1 0 0]\n",
      " [1 1 1 1 0 1 0 1 0 0]\n",
      " [1 1 0 1 0 0 1 0 1 0]\n",
      " [1 1 1 0 1 1 1 1 1 1]]\n",
      "Output:\n",
      "[[3. 4. 4. 4. 4. 5. 4. 3. 1. 0.]\n",
      " [4. 5. 5. 5. 5. 5. 4. 4. 2. 1.]\n",
      " [4. 6. 6. 6. 5. 4. 2. 3. 2. 2.]\n",
      " [2. 4. 6. 7. 5. 2. 0. 3. 3. 3.]\n",
      " [3. 5. 7. 7. 5. 3. 1. 3. 2. 2.]\n",
      " [3. 4. 5. 5. 4. 3. 2. 3. 2. 1.]\n",
      " [5. 6. 6. 4. 4. 3. 4. 3. 2. 0.]\n",
      " [5. 6. 6. 4. 4. 3. 4. 4. 3. 1.]\n",
      " [6. 8. 7. 5. 5. 5. 6. 6. 5. 3.]\n",
      " [4. 5. 4. 3. 3. 4. 4. 5. 4. 3.]]\n"
     ]
    }
   ],
   "source": [
    "test_convolve2d(grid, np.ones((3, 3)), mode='same')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[3., 3., 4., 3., 3., 5., 3., 2., 1., 0.],\n",
       "       [3., 4., 4., 5., 4., 4., 3., 4., 2., 1.],\n",
       "       [3., 6., 6., 5., 5., 4., 2., 3., 1., 2.],\n",
       "       [2., 3., 5., 6., 4., 2., 0., 3., 2., 3.],\n",
       "       [3., 5., 6., 6., 4., 3., 1., 3., 1., 2.],\n",
       "       [2., 3., 5., 4., 4., 3., 1., 3., 2., 1.],\n",
       "       [5., 5., 6., 4., 3., 3., 4., 2., 2., 0.],\n",
       "       [4., 5., 5., 3., 4., 2., 4., 3., 3., 1.],\n",
       "       [5., 7., 7., 4., 5., 5., 5., 6., 4., 3.],\n",
       "       [3., 4., 3., 3., 2., 3., 3., 4., 3., 2.]])"
      ]
     },
     "execution_count": 146,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "nbrs_count = convolve2d(grid, np.ones((3, 3)), mode='same') - grid\n",
    "nbrs_count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 172,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1, 1, 0, 1, 1, 0, 1, 1, 0, 0],\n",
       "       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],\n",
       "       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0],\n",
       "       [0, 1, 0, 0, 0, 0, 0, 1, 1, 1],\n",
       "       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0],\n",
       "       [1, 1, 0, 0, 0, 1, 0, 1, 0, 0],\n",
       "       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0],\n",
       "       [0, 0, 0, 1, 0, 1, 0, 1, 1, 0],\n",
       "       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],\n",
       "       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1]], dtype=int32)"
      ]
     },
     "execution_count": 172,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "(nbrs_count == 3) | (grid & (nbrs_count == 2))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "See `np.bitwise_and` and `np.bitwise_or`.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
import numpy as np

### TASK 1
Re-create the numpy arrays above by entering the lines of code above into the code cell below:

In [2]:
my_array = np.array([1,2,3,4])

In [3]:
my_2d_array = np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])


In [6]:
a = np.array([True,True,False,False])
b = np.array([False,False,True,True])

In [7]:
print(my_3d_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [8]:
print(my_array)

[1 2 3 4]


## Accessing Array Attributes
For this section we retrieving information about the arrays. Once an array is created you can access information about the array such as the number of dimensions, its shape, its size, the data type that it stores, the number of bytes it is consuming. There are a variety of attributes you can use such as:
+ `ndim`
+ `shape`
+ `size`
+ `dtype`
+ `itemsize`
+ `data`
+ `nbytes`

For example, to get the number of dimensions for an array:
```Python
# Print the number of dimensions for the array:
print(my_3d_array.ndim)
```

### Task 2

In the code cell below, practice using each of the attributes above. Add a comment line, as shown in the preceeding code to describe what each attribute is for. Use the [NumPy ndarray reference page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) if you need help understanding the attributes.

_Note: Notice that we use dot notation to access these attributes, yet we do not provide the parenthesis `()` like we would for a function call.  This is because we are accessing attributes (i.e. member variables) of the numpy object, we are not calling a function_

In [27]:
my_array # print the contents of the array

array([1, 2, 3, 4])

In [28]:
my_array.ndim # print the number of dimensions of the array


1

In [29]:
my_array.size #print the size of the array

4

In [30]:
my_array.dtype # print the data type of the array

dtype('int32')

In [31]:
my_array.itemsize # print length of array size in bytes

4

In [32]:
my_array.data #python buffer object pointing to the start of the array

In [33]:
my_array.nbytes #prints the total bytes consumed by the elements of the array

16

## Creating Initialized Arrays

Here we will learn to create initialized arrays. Some refer to these as "empty" arrays, but in reality, the arrays are not empty. Rather they are pre-initalized with default values.  NumPy provides a variety of functions for creating and intializing an array in easy-to-use functions. These include: 

+ `np.ones()`
+ `np.zeroes()`
+ `np.random.random()`
+ `np.empty()`
+ `np.full()`
+ `np.arange()`
+ `np.linspace()`

For example, to create an 2-dimesional _3 x 4_ array intialized with all zeros:
```Python
  # Create an array 3x4 array initialized with zeros
  zeros = np.ones((3,4))
```

### TASK 3

Practice creating initialized arrays by using each of the functions above in the code cell below. Just as in the preceeding code example, add a comment above each function call describing what is being done.  Use the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html) to learn more about each function. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 

In [35]:
zeros = np.ones((3,4)) #creates an array 3x4 initialized with zeros

In [13]:
np.ones( 5 ) #creates a 5 number array populated by ones

array([1., 1., 1., 1., 1.])

In [14]:
np.ones( (5,5) ) #creates a 5 x 5 array populated with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones( (2, #axis 2 size all populated with 1's
          5, #axis 0 size all populated with 1's
          3) #axis 1 size all populated with 1's
       )

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.random.random( (4, 4) ) #returns random floats in the shape defined by (4,4)

array([[0.41460742, 0.6231559 , 0.0746499 , 0.78355309],
       [0.88372197, 0.93379748, 0.46650527, 0.95381829],
       [0.03907411, 0.14417341, 0.97297451, 0.77929702],
       [0.73244882, 0.2360094 , 0.20025825, 0.03075956]])

In [38]:
np.empty( (3,1) ) #gives an array of given shape and size without initializing entries

array([[1.19417031e-311],
       [0.00000000e+000],
       [4.18641611e+034]])

In [41]:
np.full( (3,4), 5 ) #returns an array of given shape and size filled with a value

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [46]:
np.arange(2,5,1) #returns evenly spaced objects of given interval start, stop, interval space

array([2, 3, 4])

In [52]:
np.linspace(2.0,10.0, num=5) #returns evenly spaced numbers over a specified interval

array([ 2.,  4.,  6.,  8., 10.])

### Task 4
Try practicing math operations by creating your own arrays of differeing sizes.  In the cell below experiment adding, multiplying or dividing two arrays of different (but compatible) sizes. Do this with two different sets of arrays.

In [26]:
np.ones( (2,2) ) + np.ones( (2, 2) )

array([[2., 2.],
       [2., 2.]])

In [56]:
np.ones( (2,4) ) + np.ones( (2,4) )

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [58]:
np.ones( (3,6) ) + np.ones( (1,6) )

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [66]:
do_it = np.random.random( (5,2,2) )
do_not = np.ones( (5,2,2) )
do_it * do_not


array([[[0.6416948 , 0.79169812],
        [0.48214387, 0.79422968]],

       [[0.91068058, 0.38119944],
        [0.58157914, 0.34958074]],

       [[0.20625468, 0.88663906],
        [0.88994234, 0.5106512 ]],

       [[0.19358407, 0.72458563],
        [0.51548792, 0.87049967]],

       [[0.43732751, 0.31553028],
        [0.40422749, 0.45800477]]])

### Task 5
Find an example of non-compatible array shapes for an operation, and explain why it fails. You can demonstrate using code or written text. If you use written text, be sure to switch the cell below to use Markdown.

In [59]:
np.ones( (3,6) ) + np.ones( (1,3) ) #the shapes are different sizes and cannot be added

ValueError: operands could not be broadcast together with shapes (3,6) (1,3) 

## NumPy Aggregate Functions
NumPy also provides a variety of functions that "aggregate" data. 
Examples of aggreagation of data include calculating the sum of every element in the array, calculating the mean, standard deviation, etc.  Below are a few examples of aggregation functions provided by numpy:

+ `np.sum()`
+ `np.min()`
+ `np.max()`
+ `np.cumsum()`
+ `np.mean()`
+ `np.median()`
+ `np.corrcoef()`
+ `np.std()`

For example:
```Python
# Calculate the sum of our demo data from above
np.sum(demo_e)
```


### Task 6
Create three to five arrays (or more as needed) and experiment with each of the aggregation functions above. For each function, add a comment line above it that describes what it does.  Use the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html) to learn more about each function.

In [62]:
demo_e = np.ones((3,4))
np.sum(demo_e) #sum of array elements over a given axis


12.0

In [63]:
np.min(demo_e) #returns min value of array

1.0

In [67]:
np.max(demo_e) #returns that max value within an array

1.0

In [68]:
np.cumsum(demo_e) #returns a cumulative sum of aspects across a given axis within an array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [69]:
np.mean(demo_e) #compute the arithmatic mean across a given axis

1.0

In [70]:
np.median(demo_e) #compute the median across a given axis

1.0

In [71]:
np.corrcoef(demo_e) #Return Pearson product-moment correlation coefficients

C:\Users\Johann\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [72]:
np.std(demo_e) #compute the standard deviation across a given axis 

0.0

### Logical Aggregate Functions
When arrays contain boolean values there are additional logical aggregation functions you can use: 

 + `logical_and()`
 + `logical_or()`    
 + `logical_not()`    
 
For example:
```Python
# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]
# Perform a logical "or":
np.logical_or(a, b)
```

### Task 7

Using the code cell below, practice using each of the three logical aggregate functions listed above.

In [73]:
a = [True, True, False, False]
b = [False, False, True, True]

np.logical_or(a, b)

array([ True,  True,  True,  True])

In [74]:
np.logical_and(a,b)

array([False, False, False, False])

In [76]:
np.logical_not(b)

array([ True,  True, False, False])

### TASK 8
Perform the following in the code cell below:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension numpy array, you will be able to write an index or slice that returns a subset of desired positions.*

In [78]:
demo_j = np.full((3,4,5), 5)
demo_k = np.ones((3,4,5))
demo_l = np.full((5,6,7), 5)


In [84]:
demo_j[1,1,1]

5

In [85]:
demo_k[1,1]

array([1., 1., 1., 1., 1.])

In [87]:
demo_l[2]

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [88]:
demo_l[2:]

array([[[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]]])

In [89]:
demo_l[2, ...]

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

### TASK 9
In the code cell below, experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones:

In [90]:
demo_j[demo_j > 1]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [91]:
demo_j[demo_j < 3]

array([], dtype=int32)

In [95]:
demo_k[demo_k == 5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [105]:
demo_k[(demo_k == 5) & (demo_k < 5)]

array([], dtype=int32)

In [106]:
demo_k[(demo_k > 2) | (demo_k <2)]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### TASK 10

In the code cell below, call `help()` on one of the following functions:
 + `np.transpose()`
 + `np.reshape()`
 + `np.resize()`
 + `np.ravel()`
 + `np.append()`
 + `np.delete()`
 + `np.concatenate()`
 + `np.vstack()`
 + `np.hstack()`
 + `np.column_stack()`
 + `np.vsplit()`
 + `np.hsplit()` 

In [107]:
help(np.ravel)

Help on function ravel in module numpy.core.fromnumeric:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index

### Task 11
Practice appending matricies to one another. In the code cell below perform the following:
 + Create a three dimensional array
 + append another row to the array
 + append another colum to the array
 + print the final results

In [136]:
who_array = np.array([[[2,3,4,5], [1,2,3,4]], [[5,6,7,8], [1,2,3,4]]])
print(who_array)
you_array = np.append(who_array, [[[7], [8]], [[9], [1]]], axis=2)
print("\n")
print(you_array)
me_array = np.append(you_array, [[[7], [4], [5], [4]]], axis=1)
print("\n")
print(me_array)

[[[2 3 4 5]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]]]


[[[2 3 4 5 7]
  [1 2 3 4 8]]

 [[5 6 7 8 9]
  [1 2 3 4 1]]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [131]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))


concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


### Task 12
Examine the output from each of the function calls in the cell above. Also, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). Can you identify what is happening with each of them?

In [7]:
# concatenate adds x to the end of the array along a given axis, assumes flat if none given
#vstack stacks the 2nd array vertically under the first
#hstack stacks the arrays horrizontally
#column stack stacks the array in columns it looks like hstack in a 2d array


In [137]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### Task 13
Examine the output from each of the functions used in the cell above. Review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). Can you identify what is happening with each of them?

In [ ]:
# hsplit splits the array horrizontally at the second index position
# vsplit splits the array vertically at the second index position